name: GitHub Actions CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        dotnet-version: ["8.0"]

    runs-on: ${{ matrix.os }}

    env:
      PGSQL_USER: postgres
      PGSQL_PASSWORD: pwd123
      PGSQL_DB: project

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{env.PGSQL_USER}}
          POSTGRES_PASSWORD: ${{env.PGSQL_PASSWORD}}
          POSTGRES_DB: ${{env.PGSQL_DB}}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build
      
      - name: Executar script SQL para criar tabela
        run:
          cat scripts\create_table_person.sql | psql -h localhost -U ${{env.PGSQL_USER}} -d ${{env.PGSQL_DB}} -p 5432

      - name: Run tests
        run: dotnet test --no-build
