name: GitHub Actions CI

on:
    push:
        branches: ["main"]

jobs:
  build:
    
    strategy:
        fail-fast: true
        matrix:
          os: [ubuntu-latest]       # [ubuntu-latest, windows-latest, macos-latest]
          dotnet-version: ["8.0"]   # ['2.1', '2.2', '3.0', '3.1', '5.0', '6.0', '7.0', '8.0']
    
    runs-on: ${{ matrix.os }}

    services:
        postgres:
          image: postgres
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pwd123
            POSTGRES_DB: project
          ports:
            - 5433:5433
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build
    
    - name: Run tests
      run: dotnet test --no-build